### ISSUE TITLE
Rear View

### ISSUE THREAD

**Issue by gohamstergo** [NateMccomb/TeslaCamViewer-legacy#14]
Latest EA release added rear cam to recordings. Can you add support?

Example filename: 2019-09-22_08-56-46-rear_view.mp4

Thanks!

**Comment by NateMccomb** [comment]
I'm currently working on a new dynamic version of the viewer that will allow the support of all 9 (technically an unlimited number of) cameras as they get added over time. This has added new challenges that I'm slowly working through including a new UI and updating the export options to support the additional cameras. 

The previous versions of TeslaCam Viewer were all hard coded for only three cameras so instead of just adding more code each time a new camera is added, I figured it was time to allow the viewer to dynamically create each player based on the camera names in each file. 

I should have a beta release of TeslaCam Viewer II in the next week or so.

Thanks for including the new file name too. I'm still waiting for the update!

Here is a sample of the new UI with 6 different camera names: 
![image](https://user-images.githubusercontent.com/9289783/65455356-0de06500-de15-11e9-8f30-69ff45209dc8.png)

**Comment by gohamstergo** [comment]
Sweet, looking forward to it!

**Comment by natrlhy** [comment]
Yep, got v10 today as well. Look forward to a new viewer that supports the back camera now

**Comment by Nakatomi2010** [comment]
While you're writing this out, please note that the rear video shows the driver's license plate.  So, I don't know if you can include an option fuzz the lower portion of the screen.  This is something I edited in OpenShot Video where I used it to cut the bottom off: https://www.youtube.com/watch?v=n8rvWgbmz1U

I can send you a copy of the original video for the rear cam if you want to know where the video should fuzz the plate a bit.

Mostly for privacy concerns and such.

Also, and this is a huge feature request I imagine, the ability to edit videos such that you can follow subjects around the car, like done in the video, would be awesome.

**Comment by jbienz** [comment]
Any updates on this or a beta release? 2019.35.5 still seems to be the latest binary and there's no branch other than master.

**Comment by gohamstergo** [comment]
beta is out for donators.

**Comment by dilorenzo1987** [comment]
how long will it take to get access after donation?

**Comment by NateMccomb** [comment]
@dilorenzo1987 usually within 1-12 hours. If you haven't received an email with the download link from TeslaCamViewer@Gmail.com then send me an email from the address that is linked to your Paypal account so I can verify your donation.
